Better provisioning

diff --git a/dev-setup b/dev-setup
--- a/dev-setup
+++ b/dev-setup
@@ -4,9 +4,9 @@
 # Example taken from http://argbash.readthedocs.io/en/stable/example.html
 #
 # ARG_OPTIONAL_BOOLEAN([selfupdate],[],[Update dev-setup],[])
-# ARG_OPTIONAL_BOOLEAN([dryrun],[],[Output only, no changes],[])
-# ARG_OPTIONAL_REPEATED([modules],[m],[Modules to provision])
-# ARG_TYPE_GROUP_SET([modules],[modules],[modules],[android,aws,core,datastores,osx,osxprep,pydata,rcm,web,all])
+# ARG_OPTIONAL_BOOLEAN([provision],[p],[Provision with given modules (default all)],[off])
+# ARG_OPTIONAL_REPEATED([modules],[m],[Modules to provision],[all])
+# ARG_TYPE_GROUP_SET([modules],[modules],[modules],[macosprep,rcm,macos,core,android,aws,datastores,pydata,web,all])
 # ARG_HELP([dev-setup installer])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
@@ -27,7 +27,7 @@ die()
 begins_with_short_option()
 {
 	local first_option all_short_options
-	all_short_options='mh'
+	all_short_options='pmh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -36,27 +36,27 @@ begins_with_short_option()
 # validators
 modules()
 {
-	local _allowed=("android" "aws" "core" "datastores" "osx" "osxprep" "pydata" "rcm" "web" "all")
+	local _allowed=("macosprep" "rcm" "macos" "core" "android" "aws" "datastores" "pydata" "web" "all")
 	local _seeking="$1"
 	for element in "${_allowed[@]}"
 	do
 		test "$element" = "$_seeking" && echo "$element" && return 0
 	done
-	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'android', 'aws', 'core', 'datastores', 'osx', 'osxprep', 'pydata', 'rcm', 'web' and 'all'" 4
+	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'macosprep', 'rcm', 'macos', 'core', 'android', 'aws', 'datastores', 'pydata', 'web' and 'all'" 4
 }
 
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_selfupdate="off"
-_arg_dryrun="off"
-_arg_modules=()
+_arg_provision="off"
+_arg_modules=(all)
 
 print_help ()
 {
 	printf '%s\n' "dev-setup installer"
-	printf 'Usage: %s [--(no-)selfupdate] [--(no-)dryrun] [-m|--modules <modules>] [-h|--help]\n' "$0"
+	printf 'Usage: %s [--(no-)selfupdate] [-p|--(no-)provision] [-m|--modules <modules>] [-h|--help]\n' "$0"
 	printf '\t%s\n' "--selfupdate,--no-selfupdate: Update dev-setup (off by default)"
-	printf '\t%s\n' "--dryrun,--no-dryrun: Output only, no changes (off by default)"
-	printf '\t%s\n' "-m,--modules: Modules to provision (one of 'android', 'aws', 'core', 'datastores', 'osx', 'osxprep', 'pydata', 'rcm', 'web' and 'all'; empty by default)"
+	printf '\t%s\n' "-p,--provision,--no-provision: Provision with given modules (default all) (off by default)"
+	printf '\t%s\n' "-m,--modules: Modules to provision (one of 'macosprep', 'rcm', 'macos', 'core', 'android', 'aws', 'datastores', 'pydata', 'web' and 'all'; default array: (all) )"
 	printf '\t%s\n' "-h,--help: Prints help"
 }
 
@@ -70,9 +70,17 @@ parse_commandline ()
 				_arg_selfupdate="on"
 				test "${1:0:5}" = "--no-" && _arg_selfupdate="off"
 				;;
-			--no-dryrun|--dryrun)
-				_arg_dryrun="on"
-				test "${1:0:5}" = "--no-" && _arg_dryrun="off"
+			-p|--no-provision|--provision)
+				_arg_provision="on"
+				test "${1:0:5}" = "--no-" && _arg_provision="off"
+				;;
+			-p*)
+				_arg_provision="on"
+				_next="${_key##-p}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
 				;;
 			-m|--modules)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
@@ -109,9 +117,22 @@ parse_commandline "$@"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
-should_provision() {
-    [[ ${_arg_dryrun} == "off" ]]
+readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+if [[ -e "${SCRIPT_DIR}/.dotfiles/tag-dev-setup/dev-setup" ]]; then
+    echo "Development mode"
+    readonly PREFIX_PATH="${SCRIPT_DIR}/.dotfiles/tag-dev-setup/dev-setup"
+else
+    readonly PREFIX_PATH=".dev-setup"
+fi
+
+
+provision_enabled() {
+    [[ ${_arg_provision} == "on" ]]
 }
+
+export _arg_provision
+export -f provision_enabled
 
 start_sudo() {
     sudo -v
@@ -127,8 +148,8 @@ stop_sudo() {
 }
 
 provision_module() {
-    local module="${1}.sh"
-    local requires_sudo=("osx" "osxprep")
+    local -r module="${PREFIX_PATH}/modules/${1}.sh"
+    local -r requires_sudo=("macos" "macosprep")
 
     if [[ ! -e ${module} ]]; then
         echo "${module} does not seem to exist, skipping."
@@ -139,9 +160,9 @@ provision_module() {
     echo "Running ${module} module"
 
     if [[ " ${requires_sudo[@]} " =~ " ${1}" ]]; then
-        should_provision && echo "( start_sudo && ${module} && stop_sudo )"
+        provision_enabled && echo "( start_sudo && ${module} && stop_sudo )"
     else
-        should_provision && echo "( ${module} )"
+        provision_enabled && echo "( ${module} )"
     fi
 }
 
@@ -150,19 +171,13 @@ provision_module() {
     cd ~
 
     if [[ ${_arg_selfupdate} == "on" ]]; then
-        if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) ]]; then
-            echo "Update via git pull"
-            should_provision && git pull origin master
-        else
-            echo "Update via tarball download and extraction"
-            should_provision && curl -#L https://github.com/omares/dev-setup/tarball/master | tar -xv --strip-components 1 --exclude={README.md,LICENSE}
-        fi
+        ${PREFIX_PATH}/update.sh
 
-        [[ ${#_arg_modules[@]} -eq 0 ]] && exit 0
+        ! provision_enabled && exit 0
     fi
 
-    if [[ ${#_arg_modules[@]} -eq 0 ]]; then
-        _PRINT_HELP=yes die "Please provide a module to install" 1
+    if ! provision_enabled ; then
+        _PRINT_HELP=yes die "Please provide the --provision switch to run dev-setup." 1
         exit 0
     fi
 
@@ -171,7 +186,7 @@ provision_module() {
     [[ ! $REPLY =~ ^[Yy]$ ]] && exit 0
 
 
-    [[ " ${_arg_modules[@]} " =~ " all " ]] && _arg_modules=("android" "aws" "core" "datastores" "osx" "osxprep" "pydata" "rcm" "web")
+    [[ " ${_arg_modules[@]} " =~ " all " ]] && _arg_modules=("macosprep" "rcm" "macos" "core" "android" "aws" "datastores" "pydata" "web")
 
     for module in "${_arg_modules[@]}"
     do
@@ -179,7 +194,7 @@ provision_module() {
     done
 
     echo "------------------------------"
-    echo "Completed running dev-setup, restart your computer to ensure all updates take effect"
+    echo "Completed running dev-setup, restart your computer to ensure all updates take effect."
     echo "------------------------------"
 
 )
